language: java

jdk:
  #- oraclejdk11
  #- openjdk11
  - openjdk8

#branches:
#  only:
#    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

before_install:
  - docker run --detach -p 2379:2379 -p 2380:2380 --name etcd quay.io/coreos/etcd:latest /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - pambrose@mac.com