language: java

jdk:
  - oraclejdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker run --detach -p 2379:2379 -p 2380:2380 --name etcd quay.io/coreos/etcd:latest /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379

notifications:
  email:
    - pambrose@mac.com